import type { Category, Product } from "@/lib/products";

export const ALL_CATEGORIES: Category[] = [
  "Teléfonos",
  "Tablets",
  "Consolas",
  "Audífonos",
  "Wearables",
  "Accesorios",
  "Otros",
];

export const SUGGESTED_BRANDS: string[] = [
  "Apple",
  "Samsung",
  "Google",
  "Xiaomi",
  "OnePlus",
  "Sony",
  "Nintendo",
  "JBL",
  "Oppo",
  "Honor",
];

/**
 * Catálogo semilla con fotos de referencia (Unsplash, licencia libre).
 * Sustituir por fotos reales del producto desde el panel de administración
 * cuando estén disponibles.
 */
export const seedProducts: Product[] = [
  {
    slug: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 17",
    tagline: "El flagship absoluto. Pantalla, batería y cámara al límite.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB", "2 TB"],
    colors: [{ name: "Negro Titanio" }, { name: "Blanco Titanio" }, { name: "Azul Titanio" }, { name: "Naranja Titanio" }],
    specs: ["Chip A19 Pro", "Sistema de cámara Pro", "Pantalla Super Retina XDR", "Titanium"],
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Deep_Blue_iPhone_17_Pro_Max.jpg/1280px-Deep_Blue_iPhone_17_Pro_Max.jpg",
  },
  {
    slug: "iphone-17-pro",
    name: "iPhone 17 Pro",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 17",
    tagline: "Potencia profesional en un tamaño perfecto.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: [{ name: "Negro Titanio" }, { name: "Blanco Titanio" }, { name: "Azul Titanio" }],
    specs: ["Chip A19 Pro", "Cámara Pro", "ProMotion 120 Hz", "USB-C"],
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/IPhone_17_Pro.jpg/1280px-IPhone_17_Pro.jpg",
  },
  {
    slug: "iphone-17",
    name: "iPhone 17",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 17",
    tagline: "Nueva generación. Ligero, rápido y brillante.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: [{ name: "Negro" }, { name: "Blanco" }, { name: "Azul" }, { name: "Rosa" }],
    specs: ["Chip A19", "Cámara dual avanzada", "Dynamic Island", "Ceramic Shield"],
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Mist_Blue_iPhone_17.jpg/1280px-Mist_Blue_iPhone_17.jpg",
  },
  {
    slug: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 16",
    tagline: "Pro Max de la generación anterior, precio imbatible.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: [{ name: "Negro Titanio" }, { name: "Desierto Titanio" }, { name: "Natural Titanio" }, { name: "Blanco Titanio" }],
    specs: ["Chip A18 Pro", "Cámara 48 MP", "Control de cámara", "Titanium"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Back_view_of_iPhone_16_Pro_Max_Natural_Titanium.jpg/1280px-Back_view_of_iPhone_16_Pro_Max_Natural_Titanium.jpg",
  },
  {
    slug: "iphone-16-pro",
    name: "iPhone 16 Pro",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 16",
    tagline: "Rendimiento Pro en formato compacto.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB", "1 TB"],
    colors: [{ name: "Negro Titanio" }, { name: "Desierto Titanio" }, { name: "Natural Titanio" }, { name: "Blanco Titanio" }],
    specs: ["Chip A18 Pro", "Cámara Pro", "Action Button", "ProMotion"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Back_view_of_iPhone_16_Pro_White_Titanium.jpg/1280px-Back_view_of_iPhone_16_Pro_White_Titanium.jpg",
  },
  {
    slug: "iphone-16",
    name: "iPhone 16",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 16",
    tagline: "Equilibrio perfecto entre potencia y precio.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: [{ name: "Negro" }, { name: "Blanco" }, { name: "Rosa" }, { name: "Verde azulado" }, { name: "Ultramarino" }],
    specs: ["Chip A18", "Cámara Fusion 48 MP", "Botón de cámara", "USB-C"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Back_view_of_iPhone_16_in_Pink.jpg/1280px-Back_view_of_iPhone_16_in_Pink.jpg",
  },
  {
    slug: "iphone-16-plus",
    name: "iPhone 16 Plus",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 16",
    tagline: "Más pantalla. Más batería. Misma generación.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: [{ name: "Negro" }, { name: "Blanco" }, { name: "Rosa" }, { name: "Verde azulado" }, { name: "Ultramarino" }],
    specs: ["Chip A18", "Pantalla 6.7\"", "Cámara Fusion", "USB-C"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Back_view_of_iPhone_16_Plus_Teal.jpg/1280px-Back_view_of_iPhone_16_Plus_Teal.jpg",
  },
  {
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 15",
    tagline: "Titanium legendario a precio de oportunidad.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: [{ name: "Negro Titanio" }, { name: "Azul Titanio" }, { name: "Blanco Titanio" }, { name: "Titanio natural" }],
    specs: ["Chip A17 Pro", "Cámara 5x", "Action Button", "USB-C"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Back_view_of_iPhone_15_Pro_Max_Natural_Titanium.jpg/1280px-Back_view_of_iPhone_15_Pro_Max_Natural_Titanium.jpg",
  },
  {
    slug: "iphone-15-pro",
    name: "iPhone 15 Pro",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 15",
    tagline: "Pro sin complicaciones. Listo para lo diario y lo creativo.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB", "1 TB"],
    colors: [{ name: "Negro Titanio" }, { name: "Azul Titanio" }, { name: "Blanco Titanio" }, { name: "Titanio natural" }],
    specs: ["Chip A17 Pro", "Cámara Pro", "Action Button", "USB-C"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Back_camera_of_iPhone_15_Pro.jpg/1280px-Back_camera_of_iPhone_15_Pro.jpg",
  },
  {
    slug: "iphone-15",
    name: "iPhone 15",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 15",
    tagline: "Dynamic Island y USB-C en el esencial de Apple.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: [{ name: "Negro" }, { name: "Azul" }, { name: "Verde" }, { name: "Amarillo" }, { name: "Rosa" }],
    specs: ["Chip A16", "Cámara 48 MP", "Dynamic Island", "USB-C"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Back_view_of_iPhone_15_Blue.jpg/1280px-Back_view_of_iPhone_15_Blue.jpg",
  },
  {
    slug: "iphone-14-pro",
    name: "iPhone 14 Pro",
    category: "Teléfonos",
    brand: "Apple",
    series: "iPhone 14",
    tagline: "Always-On y cámara Pro aún vigentes.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: [{ name: "Negro espacial" }, { name: "Plata" }, { name: "Oro" }, { name: "Morado intenso" }],
    specs: ["Chip A16", "Always-On Display", "Cámara 48 MP", "Dynamic Island"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/IPhone_14_Pro_-_black.jpg/1280px-IPhone_14_Pro_-_black.jpg",
  },
  {
    slug: "galaxy-s25-ultra",
    name: "Galaxy S25 Ultra",
    category: "Teléfonos",
    brand: "Samsung",
    series: "Galaxy S25",
    tagline: "S Pen, zoom extremo y pantalla de referencia.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: [{ name: "Negro Titanio" }, { name: "Gris Titanio" }, { name: "Azul Titanio" }, { name: "Plata" }],
    specs: ["Snapdragon elite", "S Pen", "Cámara 200 MP", "Gorilla Armor"],
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Rear_view_of_the_Samsung_Galaxy_S25_Ultra_smartphone.jpg/1280px-Rear_view_of_the_Samsung_Galaxy_S25_Ultra_smartphone.jpg",
  },
  {
    slug: "galaxy-s25-plus",
    name: "Galaxy S25+",
    category: "Teléfonos",
    brand: "Samsung",
    series: "Galaxy S25",
    tagline: "Pantalla ampla y autonomía Galaxy.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB"],
    colors: [{ name: "Azul marino" }, { name: "Gris sombra" }, { name: "Plata" }, { name: "Negro" }],
    specs: ["Pantalla Dynamic AMOLED 2X", "Carga rápida", "IP68", "AI Galaxy"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Samsung_Galaxy_S25%2B.jpg/1280px-Samsung_Galaxy_S25%2B.jpg",
  },
  {
    slug: "galaxy-s25",
    name: "Galaxy S25",
    category: "Teléfonos",
    brand: "Samsung",
    series: "Galaxy S25",
    tagline: "Compacto, potente y con IA de Samsung.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB"],
    colors: [{ name: "Azul marino" }, { name: "Gris sombra" }, { name: "Plata" }, { name: "Negro" }],
    specs: ["AI Galaxy", "Cámara triple", "IP68", "120 Hz"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/20250124_%EC%82%BC%EC%84%B1_%EA%B0%A4%EB%9F%AD%EC%8B%9C_s25.jpg/1280px-20250124_%EC%82%BC%EC%84%B1_%EA%B0%A4%EB%9F%AD%EC%8B%9C_s25.jpg",
  },
  {
    slug: "galaxy-z-fold6",
    name: "Galaxy Z Fold6",
    category: "Teléfonos",
    brand: "Samsung",
    series: "Galaxy Z",
    tagline: "Tablet y teléfono en un solo dispositivo.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: [{ name: "Negro fantasma" }, { name: "Plata sombra" }, { name: "Rosa" }, { name: "Azul marino" }],
    specs: ["Pantalla plegable", "Multitarea", "S Pen compatible", "IPX8"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Samsung_Galaxy_Z_Fold_6_%283%29.jpg/1280px-Samsung_Galaxy_Z_Fold_6_%283%29.jpg",
  },
  {
    slug: "galaxy-z-flip6",
    name: "Galaxy Z Flip6",
    category: "Teléfonos",
    brand: "Samsung",
    series: "Galaxy Z",
    tagline: "Estilo icónico. Formato plegable tipo clamshell.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB"],
    colors: [{ name: "Azul sombra" }, { name: "Plata sombra" }, { name: "Mint" }, { name: "Amarillo" }],
    specs: ["Flex Window", "AI Galaxy", "Compacto", "IPX8"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Secondary_screen_on_the_back_of_Z_Flip_6.jpg/1280px-Secondary_screen_on_the_back_of_Z_Flip_6.jpg",
  },
  {
    slug: "pixel-9-pro-xl",
    name: "Pixel 9 Pro XL",
    category: "Teléfonos",
    brand: "Google",
    series: "Pixel 9",
    tagline: "La mejor cámara computacional de Google.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: [{ name: "Obsidiana" }, { name: "Porcelana" }, { name: "Hazel" }, { name: "Rosa" }],
    specs: ["Tensor G4", "Gemini Nano", "Zoom Pro", "Pantalla LTPO"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Google_Pixel_9_Pro_XL_%28back%29.jpg/1280px-Google_Pixel_9_Pro_XL_%28back%29.jpg",
  },
  {
    slug: "pixel-9-pro",
    name: "Pixel 9 Pro",
    category: "Teléfonos",
    brand: "Google",
    series: "Pixel 9",
    tagline: "Pro en tamaño ideal. Foto y IA de primer nivel.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB", "512 GB"],
    colors: [{ name: "Obsidiana" }, { name: "Porcelana" }, { name: "Hazel" }, { name: "Rosa" }],
    specs: ["Tensor G4", "Cámara Pro", "Magic Editor", "7 años de updates"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Camera_of_Google_Pixel_9_Pro_-_1.jpg/1280px-Camera_of_Google_Pixel_9_Pro_-_1.jpg",
  },
  {
    slug: "pixel-9",
    name: "Pixel 9",
    category: "Teléfonos",
    brand: "Google",
    series: "Pixel 9",
    tagline: "Simplicidad Google. Fotos impecables.",
    priceLabel: "Consultar",
    storage: ["128 GB", "256 GB"],
    colors: [{ name: "Obsidiana" }, { name: "Porcelana" }, { name: "Peonía" }, { name: "Verde invierno" }],
    specs: ["Tensor G4", "Gemini", "Carga inalámbrica", "IP68"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Pixel_9.jpg/1280px-Pixel_9.jpg",
  },
  {
    slug: "xiaomi-15-ultra",
    name: "Xiaomi 15 Ultra",
    category: "Teléfonos",
    brand: "Xiaomi",
    series: "Xiaomi 15",
    tagline: "Óptica Leica. Flagship fotográfico.",
    priceLabel: "Consultar",
    storage: ["512 GB", "1 TB"],
    colors: [{ name: "Negro" }, { name: "Blanco" }, { name: "Verde" }],
    specs: ["Leica Optics", "Snapdragon elite", "Carga hiper rápida", "IP68"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Xiaomi_15_Ultra.jpg/1280px-Xiaomi_15_Ultra.jpg",
  },
  {
    slug: "oneplus-13",
    name: "OnePlus 13",
    category: "Teléfonos",
    brand: "OnePlus",
    series: "OnePlus",
    tagline: "Velocidad, carga y rendimiento sin fricción.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: [{ name: "Negro" }, { name: "Azul" }, { name: "Blanco" }],
    specs: ["Snapdragon elite", "Hasselblad", "Carga 100W", "OxygenOS"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/OnePlus_13_back.jpg/1280px-OnePlus_13_back.jpg",
  },
  {
    slug: "sony-xperia-1-vi",
    name: "Sony Xperia 1 VI",
    category: "Teléfonos",
    brand: "Sony",
    series: "Xperia",
    tagline: "Cine y foto profesionales en formato 21:9.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB"],
    colors: [{ name: "Negro" }, { name: "Plata" }, { name: "Verde khaki" }],
    specs: ["Pantalla 4K CinemaWide", "Óptica ZEISS", "3.5 mm jack", "MicroSD"],
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Xperia1VI-01.jpg",
  },
  {
    slug: "oppo-find-x8-pro",
    name: "OPPO Find X8 Pro",
    category: "Teléfonos",
    brand: "Oppo",
    series: "Find X",
    tagline: "Diseño premium y cámara Hasselblad-level.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB"],
    colors: [{ name: "Negro espacial" }, { name: "Azul glaciares" }, { name: "Blanco" }],
    specs: ["Pantalla LTPO", "Zoom periscopio", "Carga rápida", "IP68"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/OPPO_Find_X8_Pro_white_back.png/1280px-OPPO_Find_X8_Pro_white_back.png",
  },
  {
    slug: "honor-magic7-pro",
    name: "Honor Magic7 Pro",
    category: "Teléfonos",
    brand: "Honor",
    series: "Magic",
    tagline: "AI flagship con batería y brillo extremos.",
    priceLabel: "Consultar",
    storage: ["256 GB", "512 GB", "1 TB"],
    colors: [{ name: "Negro" }, { name: "Gris lunar" }, { name: "Naranja" }],
    specs: ["Snapdragon elite", "Cámara AI", "Pantalla silicon-OLED", "IP68"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Honor_Magic_7_Pro_%28May_1%2C_2025%29.jpg/1280px-Honor_Magic_7_Pro_%28May_1%2C_2025%29.jpg",
  },
  {
    slug: "playstation-5",
    name: "PlayStation 5",
    category: "Consolas",
    brand: "Sony",
    series: "PlayStation 5",
    tagline: "La consola de nueva generación. Velocidad, 4K y DualSense.",
    priceLabel: "Consultar",
    storage: ["825 GB SSD"],
    colors: [{ name: "Blanco / Negro" }],
    specs: ["4K UHD", "Ray tracing", "SSD ultrarrápido", "Tempest 3D Audio"],
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Playstation_5_base_edition_with_controller_%28original%29.jpg/1280px-Playstation_5_base_edition_with_controller_%28original%29.jpg",
  },
  {
    slug: "dualsense-ps5",
    name: "Control DualSense PS5",
    category: "Consolas",
    brand: "Sony",
    series: "DualSense",
    tagline: "Retroalimentación háptica y gatillos adaptativos oficiales.",
    priceLabel: "Consultar",
    storage: [],
    colors: [
      { name: "Blanco" },
      { name: "Midnight Black" },
      { name: "Cobalt Blue" },
      { name: "Nova Pink" },
    ],
    specs: ["Háptica avanzada", "Gatillos adaptativos", "Micrófono integrado", "USB-C"],
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Playstation_5_DualSense_controller_in_Midnight_Black%2C_2026-02-07_%28front%29.jpg/1280px-Playstation_5_DualSense_controller_in_Midnight_Black%2C_2026-02-07_%28front%29.jpg",
  },
  {
    slug: "nintendo-switch-oled",
    name: "Nintendo Switch",
    category: "Consolas",
    brand: "Nintendo",
    series: "Nintendo Switch",
    tagline: "Juega en casa o en cualquier lugar. Joy-Con incluidos.",
    priceLabel: "Consultar",
    storage: ["32 GB", "64 GB OLED"],
    colors: [
      { name: "Neon rojo / azul" },
      { name: "Gris" },
      { name: "Blanco OLED" },
    ],
    specs: ["Modo TV / mesa / portátil", "Joy-Con desmontables", "Modo multijugador local"],
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Switch_OLED.jpg/1280px-Switch_OLED.jpg",
  },
  {
    slug: "nintendo-switch-pro",
    name: "Control Pro Nintendo Switch",
    category: "Consolas",
    brand: "Nintendo",
    series: "Switch Pro",
    tagline: "Ergonomía premium para sesiones largas en Switch.",
    priceLabel: "Consultar",
    storage: [],
    colors: [{ name: "Negro" }],
    specs: ["Inalámbrico", "Amiibo NFC", "Batería de larga duración", "USB-C"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Nintendo.Swtich.Pro.Controller.Black.jpg/1280px-Nintendo.Swtich.Pro.Controller.Black.jpg",
  },
  {
    slug: "jbl-flip-6",
    name: "JBL Flip 6",
    category: "Accesorios",
    brand: "JBL",
    series: "Flip",
    tagline: "Parlante portátil con sonido potente y batería para todo el día.",
    priceLabel: "Consultar",
    storage: [],
    colors: [
      { name: "Negro" },
      { name: "Azul" },
      { name: "Rojo" },
      { name: "Gris" },
    ],
    specs: ["Bluetooth", "IP67", "PartyBoost", "Hasta 12 h de batería"],
    featured: true,
    image: "https://images.unsplash.com/photo-1767796427185-ada2bf414860?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "jbl-charge-5",
    name: "JBL Charge 5",
    category: "Accesorios",
    brand: "JBL",
    series: "Charge",
    tagline: "Bajos potentes, resistencia al agua y power bank integrado.",
    priceLabel: "Consultar",
    storage: [],
    colors: [
      { name: "Negro" },
      { name: "Azul" },
      { name: "Rojo" },
      { name: "Verde" },
    ],
    specs: ["Bluetooth", "IP67", "Carga dispositivos", "Hasta 20 h de batería"],
    featured: true,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "airpods-pro-2",
    name: "AirPods Pro (2.ª generación)",
    category: "Audífonos",
    brand: "Apple",
    series: "AirPods Pro",
    tagline: "Cancelación activa de ruido y audio espacial personalizado.",
    priceLabel: "Consultar",
    storage: [],
    colors: [{ name: "Blanco" }],
    specs: ["ANC", "Audio espacial", "Chip H2", "Estuche MagSafe / USB-C"],
    featured: true,
    image: "https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?auto=format&fit=crop&w=1200&q=80",
  },
  {
    slug: "airpods-4",
    name: "AirPods 4",
    category: "Audífonos",
    brand: "Apple",
    series: "AirPods",
    tagline: "Diseño open-ear, comodidad todo el día y sonido Apple.",
    priceLabel: "Consultar",
    storage: [],
    colors: [{ name: "Blanco" }],
    specs: ["Chip H2", "Emparejamiento instantáneo", "Estuche de carga", "Siri"],
    featured: true,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Airpods_4.jpg/1280px-Airpods_4.jpg",
  },
];
